### ISSUE TITLE
书本上的4.3练习这样改会更加严谨一点

### ISSUE THREAD

**Issue by chichungceng** [zhanwen/AlgorithmDiagram#11]
原代码：
def max(arr):
    if len(arr) == 2:
        return arr[0] if arr[0]>arr[1] else arr[1]
    else:
        sub_max = max(arr[1:])
        return arr[0] if arr[0]>sub_max else sub_max

修改后：
def max(arr):
    if len(arr) == 1:
        return arr[0]
    elif len(arr) == 2:
        return arr[0] if arr[0]>arr[1] else arr[1]
    else:
        sub_max = max(arr[1:])
        return arr[0] if arr[0]>sub_max else sub_max

**Comment by zhanwen** [comment]
书上的更易于理解哦
